### PR TITLE
Link fix

### PR DESCRIPTION
**Pull request by c0d3st0rm**
I assume that this means the Python version.

### CODE REVIEW

**Comment by bmc** [comment]
No, actually, the file should work with both the Python and Go versions. The Go version doesn't need an index file.

**Comment by c0d3st0rm** [comment]
Then it shouldn't really be a half link, should it?

**Comment by bmc** [comment]
Probably not. I'll correct that.

**Comment by c0d3st0rm** [comment]
Cheers 👍

**Pull request closed without merging**
